/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AccountForGoods.Menu.Shop;

import AccountForGoods.Menu.FileSysModel;
import AccountForGoods.Menu.Goods;
import java.io.File;
import java.awt.event.MouseEvent;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Vitalik
 */
public class AddGoodsWithStorage extends javax.swing.JFrame {

    String PathToFile = "";
    static String Path = "";
    Goods GDS = new Goods();
    FileSysModel f;

    public AddGoodsWithStorage(String Path) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Path = Path;
        f = new FileSysModel(new File("Склади\\"));
        JTreeStorage.setModel(f);
        ImageIcon img = new ImageIcon("src\\icon\\Shop.png");
        this.setIconImage(img.getImage());
        this.setVisible(true);
        this.setTitle("Nice Shop: Додати товар із складу");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTreeStorage = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableCounters = new javax.swing.JTable();
        BtnGoodsInShop = new javax.swing.JButton();
        SpnrQualyte = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        JTreeStorage.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTreeStorage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTreeStorageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTreeStorage);

        JTableCounters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Назва", "Індекс", "Кількість", "Ціна (грн)", "Виробник"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JTableCounters);

        BtnGoodsInShop.setEnabled(false);
        BtnGoodsInShop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnGoodsInShop.setText("Додати на привалок");
        BtnGoodsInShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGoodsInShopActionPerformed(evt);
            }
        });

        SpnrQualyte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SpnrQualyte.setEnabled(false);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Відминити");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnGoodsInShop, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SpnrQualyte, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGoodsInShop, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpnrQualyte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTreeStorageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTreeStorageMouseClicked
        TreePath Path = JTreeStorage.getPathForLocation(evt.getX(), evt.getY());
        DefaultTableModel ModelJTableCounters = (DefaultTableModel) JTableCounters.getModel();
        ModelJTableCounters.setRowCount(0);
        if (Path != null) {
            PathToFile = "";
            for (int i = 0; i < Path.getPathCount(); i++) {
                PathToFile += Path.getPathComponent(i) + "\\";
            }
            if (evt.getButton() == MouseEvent.BUTTON1) {
                try {
                    ArrayList<String> textFiles = new ArrayList<String>();
                    textFiles = textFiles(PathToFile, ".json");
                    for (String s : textFiles) {
                        GDS = GDS.FromGson(GDS.ReadGsonFile(PathToFile + s), GDS);
                        ModelJTableCounters.addRow(new Object[]{GDS.GetName(), GDS.GetIndex(), GDS.GetQuantity(), GDS.GetPrice(), GDS.GetProducer()});
                    }

                } catch (Exception ex) {
                    System.out.println("error");
                }
            }
            if (evt.getButton() == MouseEvent.BUTTON3) {
                GDS = GDS.FromGson(GDS.ReadGsonFile(PathToFile), GDS);
                int max = GDS.GetQuantity();
                int min = 0;
                int step = 1;
                int initValue = 0;
                SpinnerModel modelSp = new SpinnerNumberModel(initValue, min, max, step);
                SpnrQualyte.setModel(modelSp);

                SpnrQualyte.setEnabled(true);
                BtnGoodsInShop.setEnabled(true);
            }
        }
    }//GEN-LAST:event_JTreeStorageMouseClicked

    private void BtnGoodsInShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGoodsInShopActionPerformed
        GDS.SetQuantity(GDS.GetQuantity() - (int) SpnrQualyte.getValue());
        GDS.WriteGsonFile(PathToFile, GDS.GoToGson(GDS));
        
        Path path = Paths.get(Path + "\\На прилавках\\" + GDS.GetName() + ".json");
        if (!Files.exists(path)) {
            GDS.SetQuantity((int) SpnrQualyte.getValue());
            GDS.WriteGsonFile(Path + "\\На прилавках\\" + GDS.GetName()+ ".json", GDS.GoToGson(GDS));
        }else{
            GDS = GDS.FromGson(GDS.ReadGsonFile(Path + "\\На прилавках\\" + GDS.GetName()+ ".json"), GDS);
            GDS.SetQuantity(GDS.GetQuantity() + (int) SpnrQualyte.getValue());
            GDS.WriteGsonFile(Path + "\\На прилавках\\" + GDS.GetName()+ ".json", GDS.GoToGson(GDS));
        }

        this.setVisible(false);
        AccountForGoods.Menu.Menu m = new AccountForGoods.Menu.Menu();
        m.setVisible(true);
    }//GEN-LAST:event_BtnGoodsInShopActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        AccountForGoods.Menu.Menu m = new AccountForGoods.Menu.Menu();
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGoodsWithStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGoodsWithStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGoodsWithStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGoodsWithStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGoodsWithStorage(Path).setVisible(true);
            }
        });
    }

    public ArrayList<String> textFiles(String directory, String f) {
        ArrayList<String> textFiles = new ArrayList<String>();
        File dir = new File(directory);
        for (File file : dir.listFiles()) {
            if (file.getName().endsWith((f))) {
                textFiles.add(file.getName());
            }
        }
        return textFiles;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGoodsInShop;
    private javax.swing.JTable JTableCounters;
    private javax.swing.JTree JTreeStorage;
    private javax.swing.JSpinner SpnrQualyte;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
