/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AccountForGoods.Menu;

import AccountForGoods.Menu.Shop.*;
import AccountForGoods.Menu.Storage.*;
import java.awt.event.KeyEvent;

import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.tree.TreePath;

/**
 *
 * @author Vitalik
 */
public class Menu extends javax.swing.JFrame {

    String PathToFile = "";
    Goods GDS = new Goods();
    FileSysModel f;
    Shops m = new Shops();
    Shops.Cashier r = m.new Cashier();
    String Name = "";
    double pay;
    double p = 0;

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        f = new FileSysModel(new File("Магазини\\"));
        JTreeShop.setModel(f);
        f = new FileSysModel(new File("Склади\\"));
        JTreeStorage.setModel(f);
        
        this.setTitle("Nice Shop");
        ImageIcon img = new ImageIcon("src\\icon\\Shop.png");
        this.setIconImage(img.getImage());
        this.setVisible(true);
        
        BtnAddGoodsWithStorageIcon.setToolTipText("Додати товар зі складу");
        BtnAddGoodsIcon.setToolTipText("Додати товар");
        BtnAddShopIcon.setToolTipText("Додати магазин");
        BtnRemoveShopIcon.setToolTipText("Видалити");
        BtnAddCashierIcon.setToolTipText("Додати касира");
        BtnReportIcon.setToolTipText("Звіт по касі");
        BtnAddStorageIcon.setToolTipText("Додати склад");
        BtnAddGoodsStorageIcon.setToolTipText("Додати товар");
        BtnAddСategoryIcon.setToolTipText("Додати категорію");
        BtnRemoveStorageIcon.setToolTipText("Видалити");
        
        BtnRemoveShopIcon.setEnabled(false);
        BtnAddGoodsWithStorageIcon.setEnabled(false);
        BtnAddGoodsIcon.setEnabled(false);
        BtnAddShopIcon.setEnabled(false);
        BtnAddStorageIcon.setEnabled(false);
        BtnAddGoodsStorageIcon.setEnabled(false);
        BtnAddСategoryIcon.setEnabled(false);
        BtnRemoveStorageIcon.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Shop = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTreeShop = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableCounters = new javax.swing.JTable();
        BtnPie = new javax.swing.JButton();
        LblPrice = new javax.swing.JLabel();
        SpnrQualyte = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        Pay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        IconCashRegister = new javax.swing.JPanel();
        BtnAddGoodsWithStorageIcon = new javax.swing.JButton();
        BtnAddGoodsIcon = new javax.swing.JButton();
        BtnAddShopIcon = new javax.swing.JButton();
        BtnRemoveShopIcon = new javax.swing.JButton();
        BtnAddCashierIcon = new javax.swing.JButton();
        BtnReportIcon = new javax.swing.JButton();
        FilterTable = new javax.swing.JTextField();
        jComBoxCasa = new javax.swing.JComboBox<>();
        LblFind = new javax.swing.JLabel();
        LblChooseCashRegister = new javax.swing.JLabel();
        LblReshta = new javax.swing.JLabel();
        Storage = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTreeStorage = new javax.swing.JTree();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTableCounters1 = new javax.swing.JTable();
        FilterTable1 = new javax.swing.JTextField();
        IconStorage = new javax.swing.JPanel();
        BtnAddStorageIcon = new javax.swing.JButton();
        BtnAddGoodsStorageIcon = new javax.swing.JButton();
        BtnAddСategoryIcon = new javax.swing.JButton();
        BtnRemoveStorageIcon = new javax.swing.JButton();
        LblFound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Лол");

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        JTreeShop.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTreeShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTreeShopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTreeShop);

        JTableCounters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Назва", "Індекс", "Кількість", "Ціна (грн)", "Виробник"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTableCounters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableCountersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTableCounters);

        BtnPie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnPie.setText("Купити");
        BtnPie.setEnabled(false);
        BtnPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPieActionPerformed(evt);
            }
        });

        LblPrice.setEnabled(false);
        LblPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblPrice.setText("Ціна: ");

        SpnrQualyte.setEnabled(false);
        SpnrQualyte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SpnrQualyte.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpnrQualyteStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Кількість");

        Pay.setEnabled(false);
        Pay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PayKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Оплата за товар:");

        IconCashRegister.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Операції", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        IconCashRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IconCashRegister.setPreferredSize(new java.awt.Dimension(100, 73));

        BtnAddGoodsWithStorageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add2.png"))); // NOI18N
        BtnAddGoodsWithStorageIcon.setBorder(null);
        BtnAddGoodsWithStorageIcon.setContentAreaFilled(false);
        BtnAddGoodsWithStorageIcon.setFocusPainted(false);
        BtnAddGoodsWithStorageIcon.setMargin(new java.awt.Insets(1, 1, 1, 1));
        BtnAddGoodsWithStorageIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddGoodsWithStorageIconActionPerformed(evt);
            }
        });

        BtnAddGoodsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-product.png"))); // NOI18N
        BtnAddGoodsIcon.setBorder(null);
        BtnAddGoodsIcon.setContentAreaFilled(false);
        BtnAddGoodsIcon.setFocusPainted(false);
        BtnAddGoodsIcon.setMargin(new java.awt.Insets(1, 1, 1, 1));
        BtnAddGoodsIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddGoodsIconActionPerformed(evt);
            }
        });

        BtnAddShopIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shop-product.png"))); // NOI18N
        BtnAddShopIcon.setBorder(null);
        BtnAddShopIcon.setContentAreaFilled(false);
        BtnAddShopIcon.setFocusPainted(false);
        BtnAddShopIcon.setMargin(new java.awt.Insets(1, 1, 1, 1));
        BtnAddShopIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddShopIconActionPerformed(evt);
            }
        });

        BtnRemoveShopIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        BtnRemoveShopIcon.setBorder(null);
        BtnRemoveShopIcon.setContentAreaFilled(false);
        BtnRemoveShopIcon.setFocusPainted(false);
        BtnRemoveShopIcon.setMargin(new java.awt.Insets(1, 1, 1, 1));
        BtnRemoveShopIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoveShopIconActionPerformed(evt);
            }
        });

        BtnAddCashierIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add_Cashier.png"))); // NOI18N
        BtnAddCashierIcon.setEnabled(false);
        BtnAddCashierIcon.setBorder(null);
        BtnAddCashierIcon.setContentAreaFilled(false);
        BtnAddCashierIcon.setFocusPainted(false);
        BtnAddCashierIcon.setMargin(new java.awt.Insets(1, 1, 1, 1));
        BtnAddCashierIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddCashierIconActionPerformed(evt);
            }
        });

        BtnReportIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Report1.png"))); // NOI18N
        BtnReportIcon.setEnabled(false);
        BtnReportIcon.setBorder(null);
        BtnReportIcon.setContentAreaFilled(false);
        BtnReportIcon.setFocusPainted(false);
        BtnReportIcon.setMargin(new java.awt.Insets(1, 1, 1, 1));
        BtnReportIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReportIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IconCashRegisterLayout = new javax.swing.GroupLayout(IconCashRegister);
        IconCashRegister.setLayout(IconCashRegisterLayout);
        IconCashRegisterLayout.setHorizontalGroup(
            IconCashRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconCashRegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAddGoodsWithStorageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAddGoodsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnAddShopIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(BtnRemoveShopIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAddCashierIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(BtnReportIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );
        IconCashRegisterLayout.setVerticalGroup(
            IconCashRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconCashRegisterLayout.createSequentialGroup()
                .addGroup(IconCashRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IconCashRegisterLayout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(BtnRemoveShopIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnAddCashierIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnReportIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAddGoodsIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAddShopIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, IconCashRegisterLayout.createSequentialGroup()
                        .addComponent(BtnAddGoodsWithStorageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        FilterTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FilterTableKeyReleased(evt);
            }
        });

        jComBoxCasa.setToolTipText("");

        LblFind.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblFind.setText("Знайти:");
        LblFind.setToolTipText("");

        LblChooseCashRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblChooseCashRegister.setText("Виберіть касу:");

        LblReshta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblReshta.setText("Решта:");

        javax.swing.GroupLayout ShopLayout = new javax.swing.GroupLayout(Shop);
        Shop.setLayout(ShopLayout);
        ShopLayout.setHorizontalGroup(
            ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShopLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShopLayout.createSequentialGroup()
                        .addGroup(ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblChooseCashRegister)
                            .addGroup(ShopLayout.createSequentialGroup()
                                .addComponent(jComBoxCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblPrice)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ShopLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(ShopLayout.createSequentialGroup()
                                .addComponent(SpnrQualyte, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(LblReshta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnPie, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(183, 183, 183))
                    .addGroup(ShopLayout.createSequentialGroup()
                        .addGroup(ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ShopLayout.createSequentialGroup()
                                .addComponent(LblFind)
                                .addGap(18, 18, 18)
                                .addComponent(FilterTable, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148))))
            .addComponent(IconCashRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
        );
        ShopLayout.setVerticalGroup(
            ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShopLayout.createSequentialGroup()
                .addComponent(IconCashRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblChooseCashRegister)
                        .addGap(5, 5, 5)
                        .addGroup(ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpnrQualyte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComBoxCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPrice))
                        .addGap(18, 18, 18)
                        .addGroup(ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FilterTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblFind))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(ShopLayout.createSequentialGroup()
                        .addGroup(ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ShopLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(ShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LblReshta)
                                    .addComponent(BtnPie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ShopLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Каса", Shop);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        JTreeStorage.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTreeStorage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTreeStorageMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JTreeStorage);

        JTableCounters1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Назва", "Індекс", "Кількість", "Ціна (грн)", "Виробник"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(JTableCounters1);

        FilterTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FilterTable1KeyReleased(evt);
            }
        });

        IconStorage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Операції", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        BtnAddStorageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addStorage.png"))); // NOI18N
        BtnAddStorageIcon.setContentAreaFilled(false);
        BtnAddStorageIcon.setFocusPainted(false);
        BtnAddStorageIcon.setMargin(new java.awt.Insets(1, 1, 1, 1));
        BtnAddStorageIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddStorageIconActionPerformed(evt);
            }
        });

        BtnAddGoodsStorageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-product.png"))); // NOI18N
        BtnAddGoodsStorageIcon.setContentAreaFilled(false);
        BtnAddGoodsStorageIcon.setFocusPainted(false);
        BtnAddGoodsStorageIcon.setMargin(new java.awt.Insets(1, 1, 1, 1));
        BtnAddGoodsStorageIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddGoodsStorageIconActionPerformed(evt);
            }
        });

        BtnAddСategoryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/folder-add.png"))); // NOI18N
        BtnAddСategoryIcon.setContentAreaFilled(false);
        BtnAddСategoryIcon.setFocusPainted(false);
        BtnAddСategoryIcon.setMargin(new java.awt.Insets(1, 1, 1, 1));
        BtnAddСategoryIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddСategoryIconActionPerformed(evt);
            }
        });

        BtnRemoveStorageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        BtnRemoveStorageIcon.setContentAreaFilled(false);
        BtnRemoveStorageIcon.setFocusPainted(false);
        BtnRemoveStorageIcon.setMargin(new java.awt.Insets(1, 1, 1, 1));
        BtnRemoveStorageIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoveStorageIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IconStorageLayout = new javax.swing.GroupLayout(IconStorage);
        IconStorage.setLayout(IconStorageLayout);
        IconStorageLayout.setHorizontalGroup(
            IconStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconStorageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAddStorageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAddGoodsStorageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAddСategoryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnRemoveStorageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
        );
        IconStorageLayout.setVerticalGroup(
            IconStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconStorageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(IconStorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnRemoveStorageIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(BtnAddСategoryIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(BtnAddGoodsStorageIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(BtnAddStorageIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
        );

        LblFound.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblFound.setText("Знайти:");

        javax.swing.GroupLayout StorageLayout = new javax.swing.GroupLayout(Storage);
        Storage.setLayout(StorageLayout);
        StorageLayout.setHorizontalGroup(
            StorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StorageLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StorageLayout.createSequentialGroup()
                        .addComponent(LblFound)
                        .addGap(18, 18, 18)
                        .addComponent(FilterTable1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)))
            .addComponent(IconStorage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        StorageLayout.setVerticalGroup(
            StorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StorageLayout.createSequentialGroup()
                .addComponent(IconStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StorageLayout.createSequentialGroup()
                        .addGroup(StorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblFound)
                            .addComponent(FilterTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)))
        );

        jTabbedPane1.addTab("Склади", Storage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Windows");

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FilterTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FilterTable1KeyReleased
        Filter(FilterTable.getText());
    }//GEN-LAST:event_FilterTable1KeyReleased

    private void JTreeStorageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTreeStorageMouseClicked
        TreePath Path = JTreeStorage.getPathForLocation(evt.getX(), evt.getY());
        DefaultTableModel ModelJTableCounters = (DefaultTableModel) JTableCounters1.getModel();
        ModelJTableCounters.setRowCount(0);
        if (Path != null) {
            PathToFile = "";
            for (int i = 0; i < Path.getPathCount(); i++) {
                PathToFile += Path.getPathComponent(i) + "\\";
            }
            if (evt.getButton() == MouseEvent.BUTTON1) {
                try {
                    ArrayList<String> textFiles = new ArrayList<>();
                    textFiles = textFiles(PathToFile, ".json");
                    for (String s : textFiles) {
                        GDS = GDS.FromGson(GDS.ReadGsonFile(PathToFile + s), GDS);
                        ModelJTableCounters.addRow(new Object[]{GDS.GetName(), GDS.GetIndex(), GDS.GetQuantity(), GDS.GetPrice(), GDS.GetProducer()});
                    }

                } catch (Exception ex) {
                    System.out.println("error");
                }
            }
            if (evt.getButton() == MouseEvent.BUTTON3) {
                BtnAddGoodsStorageIcon.setEnabled(true);
                BtnAddStorageIcon.setEnabled(true);
                BtnAddСategoryIcon.setEnabled(true);
                BtnRemoveStorageIcon.setEnabled(true);
            }
        }
    }//GEN-LAST:event_JTreeStorageMouseClicked

    private void BtnPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPieActionPerformed
        GDS = new Goods();
        GDS = GDS.FromGson(GDS.ReadGsonFile(PathToFile + "На прилавках\\" + Name + ".json"), GDS);
        GDS.SetQuantity(GDS.GetQuantity() - (int) SpnrQualyte.getValue());
        GDS.WriteGsonFile(PathToFile + "На прилавках\\" + Name + ".json", GDS.GoToGson(GDS));
        String[] tokens = PathToFile.split("\\\\");
        m.SetName(tokens[1]);
        r = r.FromGson(r.ReadGsonFile(PathToFile + jComBoxCasa.getSelectedItem() + ".json"), r);
        f = new FileSysModel(new File("Магазини\\"));
        JTreeShop.setModel(f);
        BtnPie.setEnabled(false);
        pay = 0;
        p = 0;
        LblPrice.setText("Ціна: ");
        Pay.setText("");
        SpnrQualyte.setValue(0);
        LblReshta.setText("");
        LblPrice.setEnabled(false);
        Pay.setEnabled(false);
        SpnrQualyte.setEnabled(false);
        DefaultTableModel ModelJTableCounters = (DefaultTableModel) JTableCounters1.getModel();
        ModelJTableCounters.setRowCount(0);
    }//GEN-LAST:event_BtnPieActionPerformed

    private void FilterTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FilterTableKeyReleased
        Filter(FilterTable.getText());
    }//GEN-LAST:event_FilterTableKeyReleased

    private void JTableCountersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableCountersMouseClicked
        LblPrice.setEnabled(true);
        SpnrQualyte.setEnabled(true);
        Pay.setEnabled(true);
        int index = JTableCounters.getSelectedRow();
        TableModel model = JTableCounters.getModel();
        int max = Integer.parseInt(model.getValueAt(index, 2).toString());
        int min = 0;
        int step = 1;
        int initValue = 0;
        SpinnerModel modelSp = new SpinnerNumberModel(initValue, min, max, step);
        SpnrQualyte.setModel(modelSp);
        Name = model.getValueAt(index, 0).toString();
        LblPrice.setText("Ціна: " + Double.parseDouble(model.getValueAt(index, 3).toString()) * (int) SpnrQualyte.getValue() + " грн");


    }//GEN-LAST:event_JTableCountersMouseClicked

    private void JTreeShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTreeShopMouseClicked
        TreePath Path = JTreeShop.getPathForLocation(evt.getX(), evt.getY());
        DefaultTableModel ModelJTableCounters = (DefaultTableModel) JTableCounters.getModel();
        ModelJTableCounters.setRowCount(0);
        if (Path != null) {
            PathToFile = "";
            for (int i = 0; i < Path.getPathCount(); i++) {
                PathToFile += Path.getPathComponent(i) + "\\";
            }
            if (evt.getButton() == MouseEvent.BUTTON1 & !PathToFile.equals("Магазини\\")) {
                ArrayList<String> textFiles = new ArrayList<>();
                textFiles = textFiles(PathToFile + "\\На прилавках\\", ".json");
                for (String s : textFiles) {
                    GDS = GDS.FromGson(GDS.ReadGsonFile(PathToFile + "\\На прилавках\\" + s), GDS);
                    ModelJTableCounters.addRow(new Object[]{GDS.GetName(), GDS.GetIndex(), GDS.GetQuantity(), GDS.GetPrice(), GDS.GetProducer()});
                }
            }
            if (evt.getButton() == MouseEvent.BUTTON3) {
                BtnAddGoodsIcon.setEnabled(true);
                BtnAddGoodsWithStorageIcon.setEnabled(true);
                BtnAddShopIcon.setEnabled(true);
                BtnRemoveShopIcon.setEnabled(true);
                BtnAddCashierIcon.setEnabled(true);
                BtnReportIcon.setEnabled(true);
            }
            jComBoxCasa.removeAllItems();
            textFiles(PathToFile, ".json").forEach(d -> {
                String[] tokens = d.split("\\.(?=[^\\.]+$)");
                jComBoxCasa.addItem(tokens[0]);
            });
        }
    }//GEN-LAST:event_JTreeShopMouseClicked

    private void SpnrQualyteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpnrQualyteStateChanged
        int index = JTableCounters.getSelectedRow();
        TableModel model = JTableCounters.getModel();
        LblPrice.setText("Ціна: " + Double.parseDouble(model.getValueAt(index, 3).toString()) * (int) SpnrQualyte.getValue() + " грн");
        p = Double.parseDouble(model.getValueAt(index, 3).toString()) * (int) SpnrQualyte.getValue();
    }//GEN-LAST:event_SpnrQualyteStateChanged

    private void PayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PayKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int index = JTableCounters.getSelectedRow();
            TableModel model = JTableCounters.getModel();
            p = Double.parseDouble(model.getValueAt(index, 3).toString()) * (int) SpnrQualyte.getValue();
            try {
                pay = (double) Double.parseDouble(Pay.getText());
                if (pay < p) {
                    LblReshta.setText("Недостатньо грошей");
                    BtnPie.setEnabled(false);
                } else {
                    LblReshta.setText("Решта: " + (pay - p) + " грн");
                    BtnPie.setEnabled(true);
                }
            } catch (NumberFormatException e) {
                LblReshta.setText("Невірний формат");
                BtnPie.setEnabled(false);
            }
        }
    }//GEN-LAST:event_PayKeyPressed

    private void BtnAddGoodsWithStorageIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddGoodsWithStorageIconActionPerformed
        this.setVisible(false);
        AddGoodsWithStorage add = new AddGoodsWithStorage(PathToFile);
        add.setVisible(true);
    }//GEN-LAST:event_BtnAddGoodsWithStorageIconActionPerformed

    private void BtnAddGoodsIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddGoodsIconActionPerformed
        this.setVisible(false);
        AccountForGoods.Menu.Shop.AddGoods a = new AccountForGoods.Menu.Shop.AddGoods();
        a.setVisible(true);
    }//GEN-LAST:event_BtnAddGoodsIconActionPerformed

    private void BtnAddShopIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddShopIconActionPerformed
        this.setVisible(false);
        AddShops d = new AddShops();
        d.setVisible(true);
    }//GEN-LAST:event_BtnAddShopIconActionPerformed

    private void BtnRemoveShopIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveShopIconActionPerformed
        File geleteFile = new File(PathToFile);
        recursiveDelete(geleteFile);
        f = new FileSysModel(new File("Магазини\\"));
        JTreeShop.setModel(f);
        BtnRemoveShopIcon.setEnabled(false);
        BtnAddGoodsWithStorageIcon.setEnabled(false);
        BtnAddGoodsIcon.setEnabled(false);
        BtnAddShopIcon.setEnabled(false);  
        BtnAddCashierIcon.setEnabled(false);
        BtnReportIcon.setEnabled(false);
        jComBoxCasa.removeAllItems();
    }//GEN-LAST:event_BtnRemoveShopIconActionPerformed

    private void BtnAddCashierIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddCashierIconActionPerformed
        this.setVisible(false);
        AddСashier a = new AddСashier();
        a.setVisible(true);
    }//GEN-LAST:event_BtnAddCashierIconActionPerformed

    private void BtnReportIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReportIconActionPerformed
        String[] tokens = PathToFile.split("\\\\");
        m.SetName(tokens[1]);
        r = m.new Cashier();
        r = r.FromGson(r.ReadGsonFile(PathToFile + jComBoxCasa.getSelectedItem() + ".json"), r);
        r.Selling(p);
        r.Report("Звіт по касиру " + jComBoxCasa.getSelectedItem() + ".txt", m);
        JOptionPane.showMessageDialog(null, "Звіт по касиру " + jComBoxCasa.getSelectedItem() + ".txt знаходить в головній папці програми", "Увага!", 2);
        BtnRemoveShopIcon.setEnabled(false);
        BtnAddGoodsWithStorageIcon.setEnabled(false);
        BtnAddGoodsIcon.setEnabled(false);
        BtnAddShopIcon.setEnabled(false);  
        BtnAddCashierIcon.setEnabled(false);
        BtnReportIcon.setEnabled(false);
    }//GEN-LAST:event_BtnReportIconActionPerformed

    private void BtnAddStorageIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddStorageIconActionPerformed
        this.setVisible(false);
        AddStorage add = new AddStorage();
        add.setVisible(true);
    }//GEN-LAST:event_BtnAddStorageIconActionPerformed

    private void BtnAddGoodsStorageIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddGoodsStorageIconActionPerformed
        this.setVisible(false);
        AddGoodsStorage y = new AddGoodsStorage(PathToFile);
        y.setVisible(true);
    }//GEN-LAST:event_BtnAddGoodsStorageIconActionPerformed

    private void BtnAddСategoryIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddСategoryIconActionPerformed
        this.setVisible(false);
        AddCategorys a = new AddCategorys(PathToFile);
        a.setVisible(true);
    }//GEN-LAST:event_BtnAddСategoryIconActionPerformed

    private void BtnRemoveStorageIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveStorageIconActionPerformed
        File geleteFile = new File(PathToFile);
        recursiveDelete(geleteFile);
        f = new FileSysModel(new File("Склади\\"));
        JTreeStorage.setModel(f);
    }//GEN-LAST:event_BtnRemoveStorageIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    private ArrayList<String> textFiles(String directory, String f) {
        ArrayList<String> textFiles = new ArrayList<>();
        File dir = new File(directory);
        for (File file : dir.listFiles()) {
            if (file.getName().endsWith((f))) {
                textFiles.add(file.getName());
            }
        }

        return textFiles;
    }

    public void recursiveDelete(File file) {
        if (!file.exists()) {
            return;
        }
        if (file.isDirectory()) {
            for (File q : file.listFiles()) {
                recursiveDelete(q);
            }
        }
        file.delete();
    }

    public void Filter(String Find) {
        DefaultTableModel model = (DefaultTableModel) JTableCounters.getModel();
        TableRowSorter<DefaultTableModel> filter = new TableRowSorter<>(model);
        JTableCounters.setRowSorter(filter);
        filter.setRowFilter(RowFilter.regexFilter(Find));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddCashierIcon;
    private javax.swing.JButton BtnAddGoodsIcon;
    private javax.swing.JButton BtnAddGoodsStorageIcon;
    private javax.swing.JButton BtnAddGoodsWithStorageIcon;
    private javax.swing.JButton BtnAddShopIcon;
    private javax.swing.JButton BtnAddStorageIcon;
    private javax.swing.JButton BtnAddСategoryIcon;
    private javax.swing.JButton BtnPie;
    private javax.swing.JButton BtnRemoveShopIcon;
    private javax.swing.JButton BtnRemoveStorageIcon;
    private javax.swing.JButton BtnReportIcon;
    private javax.swing.JTextField FilterTable;
    private javax.swing.JTextField FilterTable1;
    private javax.swing.JPanel IconCashRegister;
    private javax.swing.JPanel IconStorage;
    private javax.swing.JTable JTableCounters;
    private javax.swing.JTable JTableCounters1;
    private javax.swing.JTree JTreeShop;
    private javax.swing.JTree JTreeStorage;
    private javax.swing.JLabel LblChooseCashRegister;
    private javax.swing.JLabel LblFind;
    private javax.swing.JLabel LblFound;
    private javax.swing.JLabel LblPrice;
    private javax.swing.JLabel LblReshta;
    private javax.swing.JTextField Pay;
    private javax.swing.JPanel Shop;
    private javax.swing.JSpinner SpnrQualyte;
    private javax.swing.JPanel Storage;
    private javax.swing.JComboBox<String> jComBoxCasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
